### ISSUE TITLE
ImportError on M1 Mac

### ISSUE THREAD

**Issue by EdM1r** [weeping-angel/medium-apis#2]
Hello, 
Just faced an issue using your python library. I installed medium api via pip3 and now, when I'm trying to import Medium API I face an ImportError regarding incompatible architecture. Can you tell me if it's possible to fix this issue? 

Terminal output:
`ImportError: dlopen(/Users/ed/Library/Python/3.10/lib/python/site-packages/ujson.cpython-310-darwin.so, 0x0002): tried: '/Users/ed/Library/Python/3.10/lib/python/site-packages/ujson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ed/Library/Python/3.10/lib/python/site-packages/ujson.cpython-310-darwin.so' (no such file), '/Users/ed/Library/Python/3.10/lib/python/site-packages/ujson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

**Comment by weeping-angel** [comment]
Hey there!

Thanks for raising this issue. I've added the test cases for python 3.10 on all three OSes – Windows, Linux, and macOS. And fortunately, every test case has passed. 

But it seems like GitHub Actions do not run the macOS on M1 architecture, so I could not test it on that. I'll look into it further.

In the meantime, you can just replace `ujson` with python's native `json` module. Go to the file called `medium.py` in `src/medium_api` and replace `from ujson import loads` to `from json import loads`
