### ISSUE TITLE
How do I get the top topics and the followers count for that topic?

### ISSUE THREAD

**Issue by pavan-kumar-99** [weeping-angel/medium-apis#3]
How do I get the top topics and the followers count for that topic?

**Comment by weeping-angel** [comment]
Hi Pavan, Medium does not provide us with a direct way to determine the "top topics" on the platform. However, by using the "Tag Info" endpoint, you can get the following tag/topic attributes:

- Followers Count
- Number of stories
- Number of writers
- Number of latest stories
- Number of latest writers

If you have a list of topics/tags, you can get the attributes mentioned above and determine the "top" ones using your own ranking criteria.

In our Python SDK, to get the "Tag Info", please see this gist: https://gist.github.com/weeping-angel/65d7f3c442d498c9a9cf7f2d8f029465

**Comment by pavan-kumar-99** [comment]
Hey 
Do you know how I can get this tag value from medium UI ?
<img width="544" alt="image" src="https://github.com/weeping-angel/medium-api/assets/34813177/5db487fc-5583-4b64-8087-6e6f82679afb">

**Comment by weeping-angel** [comment]
There is no single list of all the tags available on Medium. As far as I know, this is kinda dynamic. However, you can create your own list of tags from various sources, such as:

- "User Info" of the "Top Writers" - See in which tags they're trending.
- "Article Info" of the "Top feed Articles" - See in which topics articles are distributed.
- "Related Tags" - If you have a tag value with you, you can see all the related tags available on Medium.

Hope this helps!
